import os 
import re
import streamlit as st
from crewai import Agent, LLM



class DiagnosisCopilotAgents():
    def __init__(self):
        self.llm1 = LLM(temperature = 0,
                        model = "groq/llama3-70b-8192",
                        api_key = os.environ['GROQ_API_KEY'])
        self.llm2 = LLM(temperature = 0.001,
                        model = "groq/llama-3.3-70b-versatile",
                        api_key = os.environ['GROQ_API_KEY'])
        self.llm3 = LLM(temperature = 0.001,
                        model = "groq/deepseek-r1-distill-llama-70b",
                        api_key = os.environ['GROQ_API_KEY'])
        self.llm4 = LLM(temperature = 0,
                        model = "groq/gemma2-9b-it",
                        api_key = os.environ['GROQ_API_KEY'])
        self.llm5 = LLM(temperature = 0,
                        model="ollama/deepseek-r1:1.5b", 
                        base_url="http://localhost:11434", )


    def schema_understanding_agent(self, metadata):
        return Agent(role = "Schema Analyst",
                    goal = f"""Analyze the structure of the dataset metadata provided {metadata} in the form of number_of_columns, column_names, column_data_types, column_description, and sample data.
                                Generate insights or a detailed schema understanding that can be used for code generation.""",
                    backstory = f"""You are an expert in analyzing data schemas and structures.
                                    You specialize in understanding structure of datasets and creating schemas.""",
                    llm = self.llm3,
                    # llm = self.llm5,
                    verbose = True,)
    
    def code_generator_agent(self, query):
        return Agent(role = "Code Generator",
                    goal = f"""Translate user queries {query} into executable code by leveraging the schema provided by the Schema Analyst.
                            Ensure the code adheres to the schema and resolves the query {query} effectively.""",
                    backstory = f"""A senior-level programmer skilled in understanding user queries {query} and dataset structures.
                                    Specializes in generating accurate and efficient code based on schemas.""",
                    llm = self.llm1,
                    # llm = self.llm5,
                    verbose = True,)
    
    def code_evaluator_agent(self, metadata):
        return Agent(role = "Code Evaluator",
                    goal = f"""Validate and debug the code generated by the Code Generator against the provided schema {metadata}.
                                Ensure correct column names are used in the code, and rectify errors only if necessary.""",
                    backstory = f"""A debugging expert focused on verifying and refining code for schema adherence.
                                Ensures the code is accurate and error-free based on the provided dataset schema.""",
                    llm = self.llm4,
                    # llm = self.llm1,
                    verbose = True,)

    def final_code_agent(self):
        return Agent(role = "Python Developer",
                    goal = """Transform raw generated Python code into a reusable, interpreter-ready function.""",
                    backstory = """You are an expert Python developer specializing in production-ready code.
                                    Your task is to encapsulate the given Python script into a well-structured, reusable function.""",
                    llm = self.llm2,
                    # llm = self.llm1,
                    verbose = True,)



class StreamToExpander:
    def __init__(self, expander):
        self.expander = expander
        self.buffer = []
        self.colors = ['red', 'green', 'blue', 'orange']  
        self.color_index = 0  

    def write(self, data):
        cleaned_data = re.sub(r'\x1B\[[0-9;]*[mK]', '', data)

        task_match_object = re.search(r'\"task\"\s*:\s*\"(.*?)\"', cleaned_data, re.IGNORECASE)
        task_match_input = re.search(r'task\s*:\s*([^\n]*)', cleaned_data, re.IGNORECASE)
        task_value = None
        if task_match_object:
            task_value = task_match_object.group(1)
        elif task_match_input:
            task_value = task_match_input.group(1).strip()

        if task_value:
            st.toast(":robot_face: " + task_value)
        
        if "Entering new CrewAgentExecutor chain" in cleaned_data:
            self.color_index = (self.color_index + 1) % len(self.colors)  

            cleaned_data = cleaned_data.replace("Entering new CrewAgentExecutor chain", f":{self.colors[self.color_index]}[Entering new CrewAgentExecutor chain]")
        
        if "CSV Analyst" in cleaned_data:
            cleaned_data = cleaned_data.replace("CSV Analyst", f":{self.colors[self.color_index]}[CSV Analyst]")
        if "CSV Co-pilot" in cleaned_data:
            cleaned_data = cleaned_data.replace("CSV Co-pilot", f":{self.colors[self.color_index]}[CSV Co-pilot]")
        if "Query Response Evaluator" in cleaned_data:
            cleaned_data = cleaned_data.replace("Query Response Evaluator", f":{self.colors[self.color_index]}[Query Response Evaluator]")
        if "Markdown Specialist" in cleaned_data:
            cleaned_data = cleaned_data.replace("Markdown Specialist", f":{self.colors[self.color_index]}[Markdown Specialist]")
        if "Finished chain" in cleaned_data:
            cleaned_data = cleaned_data.replace("Finished chain", f":{self.colors[self.color_index]}[Finished chain]")
        
        self.buffer.append(cleaned_data)
        if "\n" in data:
            self.expander.markdown(''.join(self.buffer), unsafe_allow_html=True)
            self.buffer = []